[tool.poetry]
name = "appels-a-projets"
version = "0.1.0"
description = "Collecte et classification des appels Ã  projets (API + scraping)"
authors = ["Walid <walid@example.com>"]
readme = "README.md"
packages = [{ include = "appels_a_projets" }]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.3"
python-dateutil = "^2.9.0"
pyyaml = "^6.0.1"
pandas = "^2.3.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
notebook = "^7.5.1"
ipykernel = "^7.1.0"
pandas = "^2.3.3"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
